### ISSUE TITLE
Allowed to request multiple tutors with minimum money

### ISSUE THREAD

**Issue by shaneeljames** [shaneeljames/SoftwareDesign#46]
Currently you are allowed to request a tutor with having a minimum amount of money, but you can have request multiple tutors with this minimum amount of money as the funds will only be deducted once the tutorial session has completed. As a result one may have multiple tutorial sessions without having the funds to pay for the session.

**Comment by Jadon-Jesse** [comment]
Fixed!
Now, soon as a student makes a request a credit will be deducted from his account. If for some reason he cancels or the session becomes expires or all tutors reject or no tutors are available, he gets a refund
